### ISSUE TITLE
Kibana 4.2.1 startup fails due to not accepted configuration parameter

### ISSUE THREAD

**Issue by dka23** [lesaux/puppet-kibana4#35]
After setting up kibana4 (version 4.2.1) with the kibana4 puppet module, kibana does not start due to unsupported parameter "server.basePath". Error message:

```
FATAL { [ValidationError: child "server" fails because ["basePath" is not allowed]]
  name: 'ValidationError',
  details:
   [ { message: '"basePath" is not allowed',
       path: 'server.basePath',
       type: 'object.allowUnknown',
       context: [Object] } ],
  _object:
   { pkg:
      { version: '4.2.1',
        buildNum: 9019,
        buildSha: '6584c6650d636df91957de2f16332b976ee719d1' },
     pid: { file: '/var/run/kibana.pid', exclusive: false },
     server:
      { port: 5601,
        host: '0.0.0.0',
        xsrf: [Object],
        basePath: 'undef',
        ssl: [Object] } },
  annotate: [Function] }
```

According to official docs (https://www.elastic.co/guide/en/kibana/4.2/kibana-server-properties.html) there is no such property supported (anymore?). 

Also, setting it to the string "undef" also seems strange:

``` yaml
# kibana configuration for 4.2. For a complete list of options please refer to:
# https://www.elastic.co/guide/en/kibana/current/kibana-server-properties.html

# Kibana is served by a back end server. This controls which port to use.
server.port: 5601

# The host to bind the server to.
server.host: "0.0.0.0"

# A value to use as a XSRF token. This token is sent back to the server on each request
# and required if you want to execute requests from other clients (like curl).
server.xsrf.token: "undef"

# If you are running kibana behind a proxy, and want to mount it at a path,
# specify that path here. The basePath can't end in a slash.
server.basePath: "undef"
```

Possible solution: Do not add config properties to the file at all if they are set to "undef". I will create a PR and submit it.
